# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 70c855ba3e67067a2734f19a84e220141caec52cf89cdb93ac1b9263af75af6995e5914cd56282e3c4f32b6da111782971449dcef52ab02719ef6ad53df93c92

test:
  secret_key_base: f5ffb1dbb580162c81e716d1971b254b05b2da1cf86e5bf3c912c33d5cdb7324abb1a54aaf5064cc4b2e41d0c5b8fa875f4ab3d7c21c3c2beef016aafab9c778

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
